model:
  name: Qwen/Qwen3-4B-Instruct-2507
  type: qwen
  temperature: 0.6
  top_p: 0.6
  max_length: 2048
  dtype: bf16

dataset:
  name: house_build
  type: house_build
  json_path: ../dataset/data.json
  train_split: "[:]"

output:
  base_dir: output
  save_final_model: false
  save_path: output/final_model
  verbose: false

external:
  mode: score_feedback
  original_prompt: true
  previous_response: true
  lim: 20

magrpo:
  num_agents: 2
  agent_devices: "auto"
  num_turns: 4
  num_train_epochs: 20
  agent_learning_rate: 1e-5
  logging_steps: 5
  num_generations: 2
  max_new_tokens: 512
  temperature: 0.6
  top_p: 0.6
  top_k: null
  discount: 0.9
  joint_mode: aligned
  early_termination_threshold: -0.1
  rollout_buffer_size: 1
  train_batch_size: 1
  advantage_normalization: true
  eval_interval: 0
  eval_num_samples: 0
  eval_batch_size: 1

reward_processor:
  enabled: true
  scale_factor: 1.0
  shift: -1.0

wandb:
  project: house_build
  entity: OpenMLRL
  run_name: house_build_magrpo
  dir: output
  tags: ["magrpo", "house_build"]

prompt:
  use_chat_template: true

task:
  block_agent1: [white_concrete, obsidian, stone_stairs, stone_bricks, planks, air]
  block_agent2: [white_concrete, obsidian, stone_stairs, stone_bricks, planks, air]
  max_commands: 600
  limited_resource: true
  player:
    hp: 5
  spider:
    num: 3
    atk_low: 1
    atk_high: 3
